# fly.toml app configuration file generated for wbrms-reservations-service on 2023-10-14T17:06:09+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wbrms-reservations-service"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
